name: e_learning_tunanetra_speech_recognition2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.3.1
  speech_to_text: 5.4.3
  flutter_tts: 3.3.3
  http: 0.13.4
  shimmer: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

